# adapted from https://github.com/dwyl/learn-travis/issues/31
language: node_js # elm is installed from npm (see install below)
node_js: node     # use "latest" version of Node.js

env:
  - ELM_VERSION=0.19.0

cache:
  directories: # so subsequent builds run faster
    - $HOME/.npm # https://stackoverflow.com/a/42523517/1148249

install: # install specific version of elm
  - npm install -g elm@$ELM_VERSION
  - travis_retry elm package install --yes # install main project dependencies

script:
  - make
