language: elm
elm:
  - elm0.19.0

cache:
  directories: # so subsequent builds run faster
    - $HOME/.npm # https://stackoverflow.com/a/42523517/1148249

before_install:
  - npm install -g uglify-js@3.4.9

script:
  - make clean
  - make
